### ISSUE TITLE
Attention Couple Input

### ISSUE THREAD

**Issue by Phando** [ramyma/A8R8_ComfyUI_nodes#3]
Great nodes, thank you!
Is there any way to alter the input on Attention Couple?
Currently it requires a regions. It would be cool if it could accept a region or a regions.

**Comment by ramyma** [comment]
Thanks!
You can pass a single region to the Attention Regions node.
You're suggesting that the Attention Couple node could be fed a region output from Attention Region directly?

**Comment by Phando** [comment]
You got it!In the case you want to do a single attention zone. You can skip the merging node. Maybe with a rename you could add a region-to-regionStack node. Or if a single region is passed you could wrap it as a single cell array (if that is what regions are)On Jun 28, 2024, at 5:43 PM, ramyma ***@***.***> wrote:﻿
Thanks!
You can pass a single region to the Attention Regions node.
You're suggesting that the Attention Couple node could be fed a region output from Attention Region directly?

**Comment by ramyma** [comment]
Done!
Now Attention Couple accepts a single region as well.

**Comment by Phando** [comment]
Thank you!On Jun 28, 2024, at 9:21 PM, ramyma ***@***.***> wrote:﻿
Done!
Now Attention Couple accepts a single region as well.
