### ISSUE TITLE
Can this be used with multiple loras for different areas?

### ISSUE THREAD

**Issue by andreszs** [ramyma/A8R8_ComfyUI_nodes#7]
Sorry for the ignorance, but can this plugin be used to apply different LoRas to each masked area without bleeding?

I know this can be done with the new nodes provided by the beta version, but it's painfully slow, so I'm looking for another method. Thanks.

**Comment by ramyma** [comment]
If you're asking about using different loras with different regions (with attention couple), then unfortunately it's not available out of the box.
However, someone proposed a work around in this reddit post: https://www.reddit.com/r/comfyui/comments/1dpwju8/regional_conditioning_with_lora_support_workflow/
